// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/workspace/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(context1 context.Context, s string) (model.Workspace, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Workspace, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Workspace); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Get(context1 any, s any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockRepository_Get_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(workspace model.Workspace, err error) *MockRepository_Get_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Workspace, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(context1 context.Context, pageRequest model.PageRequest) (model.Page, error) {
	ret := _mock.Called(context1, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) (model.Page, error)); ok {
		return returnFunc(context1, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) model.Page); ok {
		r0 = returnFunc(context1, pageRequest)
	} else {
		r0 = ret.Get(0).(model.Page)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PageRequest) error); ok {
		r1 = returnFunc(context1, pageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - pageRequest model.PageRequest
func (_e *MockRepository_Expecter) List(context1 any, pageRequest any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", context1, pageRequest)}
}

func (_c *MockRepository_List_Call) Run(run func(context1 context.Context, pageRequest model.PageRequest)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PageRequest
		if args[1] != nil {
			arg1 = args[1].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(page model.Page, err error) *MockRepository_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context1 context.Context, pageRequest model.PageRequest) (model.Page, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Member provides a mock function for the type MockRepository
func (_mock *MockRepository) Member(context1 context.Context, s string, s1 string) (model.Member, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Member")
	}

	var r0 model.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Member, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Member); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(model.Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Member_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Member'
type MockRepository_Member_Call struct {
	*mock.Call
}

// Member is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockRepository_Expecter) Member(context1 any, s any, s1 any) *MockRepository_Member_Call {
	return &MockRepository_Member_Call{Call: _e.mock.On("Member", context1, s, s1)}
}

func (_c *MockRepository_Member_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockRepository_Member_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Member_Call) Return(member model.Member, err error) *MockRepository_Member_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MockRepository_Member_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (model.Member, error)) *MockRepository_Member_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockRepository
func (_mock *MockRepository) Rename(context1 context.Context, s string, name model.Name, n int64) (model.Workspace, error) {
	ret := _mock.Called(context1, s, name, n)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 model.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Name, int64) (model.Workspace, error)); ok {
		return returnFunc(context1, s, name, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Name, int64) model.Workspace); ok {
		r0 = returnFunc(context1, s, name, n)
	} else {
		r0 = ret.Get(0).(model.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Name, int64) error); ok {
		r1 = returnFunc(context1, s, name, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockRepository_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - name model.Name
//   - n int64
func (_e *MockRepository_Expecter) Rename(context1 any, s any, name any, n any) *MockRepository_Rename_Call {
	return &MockRepository_Rename_Call{Call: _e.mock.On("Rename", context1, s, name, n)}
}

func (_c *MockRepository_Rename_Call) Run(run func(context1 context.Context, s string, name model.Name, n int64)) *MockRepository_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Name
		if args[2] != nil {
			arg2 = args[2].(model.Name)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Rename_Call) Return(workspace model.Workspace, err error) *MockRepository_Rename_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockRepository_Rename_Call) RunAndReturn(run func(context1 context.Context, s string, name model.Name, n int64) (model.Workspace, error)) *MockRepository_Rename_Call {
	_c.Call.Return(run)
	return _c
}
