// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/pkg/txer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactioner creates a new instance of MockTransactioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactioner {
	mock := &MockTransactioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactioner is an autogenerated mock type for the Transactioner type
type MockTransactioner struct {
	mock.Mock
}

type MockTransactioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactioner) EXPECT() *MockTransactioner_Expecter {
	return &MockTransactioner_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function for the type MockTransactioner
func (_mock *MockTransactioner) RunInTx(ctx context.Context, fn txer.TransactionFn) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, txer.TransactionFn) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactioner_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type MockTransactioner_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn txer.TransactionFn
func (_e *MockTransactioner_Expecter) RunInTx(ctx any, fn any) *MockTransactioner_RunInTx_Call {
	return &MockTransactioner_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *MockTransactioner_RunInTx_Call) Run(run func(ctx context.Context, fn txer.TransactionFn)) *MockTransactioner_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 txer.TransactionFn
		if args[1] != nil {
			arg1 = args[1].(txer.TransactionFn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactioner_RunInTx_Call) Return(err error) *MockTransactioner_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactioner_RunInTx_Call) RunAndReturn(run func(ctx context.Context, fn txer.TransactionFn) error) *MockTransactioner_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}
