// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWorker creates a new instance of MockWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorker {
	mock := &MockWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorker is an autogenerated mock type for the Worker type
type MockWorker struct {
	mock.Mock
}

type MockWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorker) EXPECT() *MockWorker_Expecter {
	return &MockWorker_Expecter{mock: &_m.Mock}
}

// RunOne provides a mock function for the type MockWorker
func (_mock *MockWorker) RunOne(context1 context.Context) (int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for RunOne")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorker_RunOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOne'
type MockWorker_RunOne_Call struct {
	*mock.Call
}

// RunOne is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockWorker_Expecter) RunOne(context1 any) *MockWorker_RunOne_Call {
	return &MockWorker_RunOne_Call{Call: _e.mock.On("RunOne", context1)}
}

func (_c *MockWorker_RunOne_Call) Run(run func(context1 context.Context)) *MockWorker_RunOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorker_RunOne_Call) Return(n int, err error) *MockWorker_RunOne_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockWorker_RunOne_Call) RunAndReturn(run func(context1 context.Context) (int, error)) *MockWorker_RunOne_Call {
	_c.Call.Return(run)
	return _c
}
