// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/membership/model"
	"github.com/chai-rs/handdraw-server/pkg/cursor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSharedBoards creates a new instance of MockSharedBoards. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSharedBoards(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSharedBoards {
	mock := &MockSharedBoards{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSharedBoards is an autogenerated mock type for the SharedBoards type
type MockSharedBoards struct {
	mock.Mock
}

type MockSharedBoards_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSharedBoards) EXPECT() *MockSharedBoards_Expecter {
	return &MockSharedBoards_Expecter{mock: &_m.Mock}
}

// SharedBoardIDs provides a mock function for the type MockSharedBoards
func (_mock *MockSharedBoards) SharedBoardIDs(context1 context.Context, pageRequest model.PageRequest) ([]string, *cursor.Position, error) {
	ret := _mock.Called(context1, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for SharedBoardIDs")
	}

	var r0 []string
	var r1 *cursor.Position
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) ([]string, *cursor.Position, error)); ok {
		return returnFunc(context1, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) []string); ok {
		r0 = returnFunc(context1, pageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PageRequest) *cursor.Position); ok {
		r1 = returnFunc(context1, pageRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cursor.Position)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.PageRequest) error); ok {
		r2 = returnFunc(context1, pageRequest)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSharedBoards_SharedBoardIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharedBoardIDs'
type MockSharedBoards_SharedBoardIDs_Call struct {
	*mock.Call
}

// SharedBoardIDs is a helper method to define mock.On call
//   - context1 context.Context
//   - pageRequest model.PageRequest
func (_e *MockSharedBoards_Expecter) SharedBoardIDs(context1 any, pageRequest any) *MockSharedBoards_SharedBoardIDs_Call {
	return &MockSharedBoards_SharedBoardIDs_Call{Call: _e.mock.On("SharedBoardIDs", context1, pageRequest)}
}

func (_c *MockSharedBoards_SharedBoardIDs_Call) Run(run func(context1 context.Context, pageRequest model.PageRequest)) *MockSharedBoards_SharedBoardIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PageRequest
		if args[1] != nil {
			arg1 = args[1].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSharedBoards_SharedBoardIDs_Call) Return(strings []string, position *cursor.Position, err error) *MockSharedBoards_SharedBoardIDs_Call {
	_c.Call.Return(strings, position, err)
	return _c
}

func (_c *MockSharedBoards_SharedBoardIDs_Call) RunAndReturn(run func(context1 context.Context, pageRequest model.PageRequest) ([]string, *cursor.Position, error)) *MockSharedBoards_SharedBoardIDs_Call {
	_c.Call.Return(run)
	return _c
}
