// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/asset/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type MockRepository
func (_mock *MockRepository) Complete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockRepository_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Complete(context1 any, s any) *MockRepository_Complete_Call {
	return &MockRepository_Complete_Call{Call: _e.mock.On("Complete", context1, s)}
}

func (_c *MockRepository_Complete_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Complete_Call) Return(err error) *MockRepository_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Complete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockRepository_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(context1 context.Context, s string) (model.Asset, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Asset, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Asset); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Asset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Get(context1 any, s any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockRepository_Get_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(asset model.Asset, err error) *MockRepository_Get_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Asset, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type MockRepository
func (_mock *MockRepository) Lock(context1 context.Context, s string, b bool) error {
	ret := _mock.Called(context1, s, b)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(context1, s, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockRepository_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - b bool
func (_e *MockRepository_Expecter) Lock(context1 any, s any, b any) *MockRepository_Lock_Call {
	return &MockRepository_Lock_Call{Call: _e.mock.On("Lock", context1, s, b)}
}

func (_c *MockRepository_Lock_Call) Run(run func(context1 context.Context, s string, b bool)) *MockRepository_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Lock_Call) Return(err error) *MockRepository_Lock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Lock_Call) RunAndReturn(run func(context1 context.Context, s string, b bool) error) *MockRepository_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type MockRepository
func (_mock *MockRepository) Reserve(context1 context.Context, s string, s1 string, reserve model.Reserve) error {
	ret := _mock.Called(context1, s, s1, reserve)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.Reserve) error); ok {
		r0 = returnFunc(context1, s, s1, reserve)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockRepository_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - reserve model.Reserve
func (_e *MockRepository_Expecter) Reserve(context1 any, s any, s1 any, reserve any) *MockRepository_Reserve_Call {
	return &MockRepository_Reserve_Call{Call: _e.mock.On("Reserve", context1, s, s1, reserve)}
}

func (_c *MockRepository_Reserve_Call) Run(run func(context1 context.Context, s string, s1 string, reserve model.Reserve)) *MockRepository_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.Reserve
		if args[3] != nil {
			arg3 = args[3].(model.Reserve)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Reserve_Call) Return(err error) *MockRepository_Reserve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Reserve_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, reserve model.Reserve) error) *MockRepository_Reserve_Call {
	_c.Call.Return(run)
	return _c
}
