// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/billing/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Observe provides a mock function for the type MockProvider
func (_mock *MockProvider) Observe(context1 context.Context, s string) (model.Snapshot, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 model.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Snapshot, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Snapshot); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Snapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type MockProvider_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockProvider_Expecter) Observe(context1 any, s any) *MockProvider_Observe_Call {
	return &MockProvider_Observe_Call{Call: _e.mock.On("Observe", context1, s)}
}

func (_c *MockProvider_Observe_Call) Run(run func(context1 context.Context, s string)) *MockProvider_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Observe_Call) Return(snapshot model.Snapshot, err error) *MockProvider_Observe_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockProvider_Observe_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Snapshot, error)) *MockProvider_Observe_Call {
	_c.Call.Return(run)
	return _c
}
