// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"

	"github.com/chai-rs/handdraw-server/app/billing/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockRepository
func (_mock *MockRepository) Apply(context1 context.Context, task model.Task, snapshot model.Snapshot) error {
	ret := _mock.Called(context1, task, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task, model.Snapshot) error); ok {
		r0 = returnFunc(context1, task, snapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockRepository_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - context1 context.Context
//   - task model.Task
//   - snapshot model.Snapshot
func (_e *MockRepository_Expecter) Apply(context1 any, task any, snapshot any) *MockRepository_Apply_Call {
	return &MockRepository_Apply_Call{Call: _e.mock.On("Apply", context1, task, snapshot)}
}

func (_c *MockRepository_Apply_Call) Run(run func(context1 context.Context, task model.Task, snapshot model.Snapshot)) *MockRepository_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Task
		if args[1] != nil {
			arg1 = args[1].(model.Task)
		}
		var arg2 model.Snapshot
		if args[2] != nil {
			arg2 = args[2].(model.Snapshot)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Apply_Call) Return(err error) *MockRepository_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Apply_Call) RunAndReturn(run func(context1 context.Context, task model.Task, snapshot model.Snapshot) error) *MockRepository_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Lease provides a mock function for the type MockRepository
func (_mock *MockRepository) Lease(context1 context.Context, s string) (model.Task, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Lease")
	}

	var r0 model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Task, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Task); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Lease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lease'
type MockRepository_Lease_Call struct {
	*mock.Call
}

// Lease is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Lease(context1 any, s any) *MockRepository_Lease_Call {
	return &MockRepository_Lease_Call{Call: _e.mock.On("Lease", context1, s)}
}

func (_c *MockRepository_Lease_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Lease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Lease_Call) Return(task model.Task, err error) *MockRepository_Lease_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockRepository_Lease_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Task, error)) *MockRepository_Lease_Call {
	_c.Call.Return(run)
	return _c
}

// Maintain provides a mock function for the type MockRepository
func (_mock *MockRepository) Maintain(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Maintain")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Maintain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Maintain'
type MockRepository_Maintain_Call struct {
	*mock.Call
}

// Maintain is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRepository_Expecter) Maintain(context1 any) *MockRepository_Maintain_Call {
	return &MockRepository_Maintain_Call{Call: _e.mock.On("Maintain", context1)}
}

func (_c *MockRepository_Maintain_Call) Run(run func(context1 context.Context)) *MockRepository_Maintain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Maintain_Call) Return(err error) *MockRepository_Maintain_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Maintain_Call) RunAndReturn(run func(context1 context.Context) error) *MockRepository_Maintain_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function for the type MockRepository
func (_mock *MockRepository) Request(context1 context.Context, s string, s1 string, s2 string, s3 string, command model.Command) (json.RawMessage, error) {
	ret := _mock.Called(context1, s, s1, s2, s3, command)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, model.Command) (json.RawMessage, error)); ok {
		return returnFunc(context1, s, s1, s2, s3, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, model.Command) json.RawMessage); ok {
		r0 = returnFunc(context1, s, s1, s2, s3, command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, model.Command) error); ok {
		r1 = returnFunc(context1, s, s1, s2, s3, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockRepository_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - s3 string
//   - command model.Command
func (_e *MockRepository_Expecter) Request(context1 any, s any, s1 any, s2 any, s3 any, command any) *MockRepository_Request_Call {
	return &MockRepository_Request_Call{Call: _e.mock.On("Request", context1, s, s1, s2, s3, command)}
}

func (_c *MockRepository_Request_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, command model.Command)) *MockRepository_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 model.Command
		if args[5] != nil {
			arg5 = args[5].(model.Command)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepository_Request_Call) Return(v json.RawMessage, err error) *MockRepository_Request_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_Request_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, command model.Command) (json.RawMessage, error)) *MockRepository_Request_Call {
	_c.Call.Return(run)
	return _c
}
