BEGIN;
DROP FUNCTION handdraw.local_billing_notices();
DROP FUNCTION handdraw.billing_maintenance();
DROP FUNCTION handdraw.apply_billing(text,text,jsonb);
DROP FUNCTION handdraw.local_billing_event(text,text,text,jsonb);
DROP FUNCTION handdraw.local_billing_prepare(text);
DROP FUNCTION handdraw.lease_billing(text);
DROP FUNCTION handdraw.billing_request(text,text,text,uuid,jsonb);
DROP FUNCTION handdraw.billing_view(text);
DROP FUNCTION handdraw.billing_access_snapshot(text);
DROP FUNCTION handdraw.billing_removals(text);
DROP TABLE handdraw.billing_notice_outbox;
DROP TABLE handdraw.retention_episodes;
DROP TABLE handdraw.payment_refunds;
DROP TABLE handdraw.payment_orders;
DROP TABLE handdraw.provider_events;
DROP TABLE handdraw.local_billing_operations;
DROP TABLE handdraw.billing_contracts;
DROP TABLE handdraw.billing_change_intents;
DROP POLICY access_purge_projects ON handdraw.projects;
REVOKE DELETE ON handdraw.projects FROM handdraw_access_owner;
DROP POLICY access_billing_manage ON handdraw.subscriptions;
REVOKE INSERT,UPDATE ON handdraw.subscriptions FROM handdraw_access_owner;
GRANT UPDATE(workspace_id) ON handdraw.subscriptions TO handdraw_access_owner;
REVOKE UPDATE(kind,lifecycle,deleted_at) ON handdraw.workspaces FROM handdraw_access_owner;
ALTER TABLE handdraw.subscriptions DROP CONSTRAINT subscriptions_provider_check;
ALTER TABLE handdraw.subscriptions ADD CONSTRAINT subscriptions_provider_check CHECK(provider='polar');
REVOKE ALL ON SCHEMA handdraw FROM handdraw_billing_runtime;
REVOKE EXECUTE ON FUNCTION handdraw.schema_compatible(bigint) FROM handdraw_billing_runtime;
DROP ROLE handdraw_billing_runtime;
COMMIT;
