// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/comment/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Comment provides a mock function for the type MockRepository
func (_mock *MockRepository) Comment(context1 context.Context, s string) (model.Comment, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Comment")
	}

	var r0 model.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Comment, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Comment); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Comment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Comment'
type MockRepository_Comment_Call struct {
	*mock.Call
}

// Comment is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Comment(context1 any, s any) *MockRepository_Comment_Call {
	return &MockRepository_Comment_Call{Call: _e.mock.On("Comment", context1, s)}
}

func (_c *MockRepository_Comment_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Comment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Comment_Call) Return(comment model.Comment, err error) *MockRepository_Comment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockRepository_Comment_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Comment, error)) *MockRepository_Comment_Call {
	_c.Call.Return(run)
	return _c
}

// Comments provides a mock function for the type MockRepository
func (_mock *MockRepository) Comments(context1 context.Context, s string, s1 string, n int) ([]model.Comment, error) {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for Comments")
	}

	var r0 []model.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) ([]model.Comment, error)); ok {
		return returnFunc(context1, s, s1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) []model.Comment); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(context1, s, s1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Comments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Comments'
type MockRepository_Comments_Call struct {
	*mock.Call
}

// Comments is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int
func (_e *MockRepository_Expecter) Comments(context1 any, s any, s1 any, n any) *MockRepository_Comments_Call {
	return &MockRepository_Comments_Call{Call: _e.mock.On("Comments", context1, s, s1, n)}
}

func (_c *MockRepository_Comments_Call) Run(run func(context1 context.Context, s string, s1 string, n int)) *MockRepository_Comments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Comments_Call) Return(comments []model.Comment, err error) *MockRepository_Comments_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockRepository_Comments_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int) ([]model.Comment, error)) *MockRepository_Comments_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(context1 context.Context, s string, s1 string, s2 string, create model.Create) error {
	ret := _mock.Called(context1, s, s1, s2, create)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, model.Create) error); ok {
		r0 = returnFunc(context1, s, s1, s2, create)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - create model.Create
func (_e *MockRepository_Expecter) Create(context1 any, s any, s1 any, s2 any, create any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", context1, s, s1, s2, create)}
}

func (_c *MockRepository_Create_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, create model.Create)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 model.Create
		if args[4] != nil {
			arg4 = args[4].(model.Create)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, create model.Create) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Document provides a mock function for the type MockRepository
func (_mock *MockRepository) Document(context1 context.Context, s string) ([]byte, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Document")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Document_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Document'
type MockRepository_Document_Call struct {
	*mock.Call
}

// Document is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Document(context1 any, s any) *MockRepository_Document_Call {
	return &MockRepository_Document_Call{Call: _e.mock.On("Document", context1, s)}
}

func (_c *MockRepository_Document_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Document_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Document_Call) Return(bytes []byte, err error) *MockRepository_Document_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRepository_Document_Call) RunAndReturn(run func(context1 context.Context, s string) ([]byte, error)) *MockRepository_Document_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function for the type MockRepository
func (_mock *MockRepository) Edit(context1 context.Context, s string, s1 string, b bool, n int64) error {
	ret := _mock.Called(context1, s, s1, b, n)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool, int64) error); ok {
		r0 = returnFunc(context1, s, s1, b, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockRepository_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - b bool
//   - n int64
func (_e *MockRepository_Expecter) Edit(context1 any, s any, s1 any, b any, n any) *MockRepository_Edit_Call {
	return &MockRepository_Edit_Call{Call: _e.mock.On("Edit", context1, s, s1, b, n)}
}

func (_c *MockRepository_Edit_Call) Run(run func(context1 context.Context, s string, s1 string, b bool, n int64)) *MockRepository_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_Edit_Call) Return(err error) *MockRepository_Edit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Edit_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, b bool, n int64) error) *MockRepository_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function for the type MockRepository
func (_mock *MockRepository) Lock(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockRepository_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Lock(context1 any, s any) *MockRepository_Lock_Call {
	return &MockRepository_Lock_Call{Call: _e.mock.On("Lock", context1, s)}
}

func (_c *MockRepository_Lock_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Lock_Call) Return(err error) *MockRepository_Lock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Lock_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockRepository_Lock_Call {
	_c.Call.Return(run)
	return _c
}

// Reply provides a mock function for the type MockRepository
func (_mock *MockRepository) Reply(context1 context.Context, s string, s1 string, s2 string) error {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for Reply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Reply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reply'
type MockRepository_Reply_Call struct {
	*mock.Call
}

// Reply is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockRepository_Expecter) Reply(context1 any, s any, s1 any, s2 any) *MockRepository_Reply_Call {
	return &MockRepository_Reply_Call{Call: _e.mock.On("Reply", context1, s, s1, s2)}
}

func (_c *MockRepository_Reply_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockRepository_Reply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Reply_Call) Return(err error) *MockRepository_Reply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Reply_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) error) *MockRepository_Reply_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockRepository
func (_mock *MockRepository) Resolve(context1 context.Context, s string, s1 string, n int64) error {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockRepository_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int64
func (_e *MockRepository_Expecter) Resolve(context1 any, s any, s1 any, n any) *MockRepository_Resolve_Call {
	return &MockRepository_Resolve_Call{Call: _e.mock.On("Resolve", context1, s, s1, n)}
}

func (_c *MockRepository_Resolve_Call) Run(run func(context1 context.Context, s string, s1 string, n int64)) *MockRepository_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Resolve_Call) Return(err error) *MockRepository_Resolve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Resolve_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int64) error) *MockRepository_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Thread provides a mock function for the type MockRepository
func (_mock *MockRepository) Thread(context1 context.Context, s string) (model.Thread, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Thread")
	}

	var r0 model.Thread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Thread, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Thread); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Thread)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Thread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Thread'
type MockRepository_Thread_Call struct {
	*mock.Call
}

// Thread is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Thread(context1 any, s any) *MockRepository_Thread_Call {
	return &MockRepository_Thread_Call{Call: _e.mock.On("Thread", context1, s)}
}

func (_c *MockRepository_Thread_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Thread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Thread_Call) Return(thread model.Thread, err error) *MockRepository_Thread_Call {
	_c.Call.Return(thread, err)
	return _c
}

func (_c *MockRepository_Thread_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Thread, error)) *MockRepository_Thread_Call {
	_c.Call.Return(run)
	return _c
}

// Threads provides a mock function for the type MockRepository
func (_mock *MockRepository) Threads(context1 context.Context, s string, s1 string, s2 string, n int) ([]model.Thread, error) {
	ret := _mock.Called(context1, s, s1, s2, n)

	if len(ret) == 0 {
		panic("no return value specified for Threads")
	}

	var r0 []model.Thread
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int) ([]model.Thread, error)); ok {
		return returnFunc(context1, s, s1, s2, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int) []model.Thread); ok {
		r0 = returnFunc(context1, s, s1, s2, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Thread)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int) error); ok {
		r1 = returnFunc(context1, s, s1, s2, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Threads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Threads'
type MockRepository_Threads_Call struct {
	*mock.Call
}

// Threads is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - n int
func (_e *MockRepository_Expecter) Threads(context1 any, s any, s1 any, s2 any, n any) *MockRepository_Threads_Call {
	return &MockRepository_Threads_Call{Call: _e.mock.On("Threads", context1, s, s1, s2, n)}
}

func (_c *MockRepository_Threads_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, n int)) *MockRepository_Threads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_Threads_Call) Return(threads []model.Thread, err error) *MockRepository_Threads_Call {
	_c.Call.Return(threads, err)
	return _c
}

func (_c *MockRepository_Threads_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, n int) ([]model.Thread, error)) *MockRepository_Threads_Call {
	_c.Call.Return(run)
	return _c
}
