// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/access/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOnboarding creates a new instance of MockOnboarding. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnboarding(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnboarding {
	mock := &MockOnboarding{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOnboarding is an autogenerated mock type for the Onboarding type
type MockOnboarding struct {
	mock.Mock
}

type MockOnboarding_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnboarding) EXPECT() *MockOnboarding_Expecter {
	return &MockOnboarding_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOnboarding
func (_mock *MockOnboarding) Create(context1 context.Context, s string, s1 string, s2 string) (model.Decision, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Decision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (model.Decision, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) model.Decision); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Get(0).(model.Decision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOnboarding_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOnboarding_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockOnboarding_Expecter) Create(context1 any, s any, s1 any, s2 any) *MockOnboarding_Create_Call {
	return &MockOnboarding_Create_Call{Call: _e.mock.On("Create", context1, s, s1, s2)}
}

func (_c *MockOnboarding_Create_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockOnboarding_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOnboarding_Create_Call) Return(decision model.Decision, err error) *MockOnboarding_Create_Call {
	_c.Call.Return(decision, err)
	return _c
}

func (_c *MockOnboarding_Create_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (model.Decision, error)) *MockOnboarding_Create_Call {
	_c.Call.Return(run)
	return _c
}
