// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/workspace/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkspaces creates a new instance of MockWorkspaces. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaces(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaces {
	mock := &MockWorkspaces{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaces is an autogenerated mock type for the Workspaces type
type MockWorkspaces struct {
	mock.Mock
}

type MockWorkspaces_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaces) EXPECT() *MockWorkspaces_Expecter {
	return &MockWorkspaces_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockWorkspaces
func (_mock *MockWorkspaces) List(context1 context.Context, pageRequest model.PageRequest) (model.Page, error) {
	ret := _mock.Called(context1, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Page
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) (model.Page, error)); ok {
		return returnFunc(context1, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) model.Page); ok {
		r0 = returnFunc(context1, pageRequest)
	} else {
		r0 = ret.Get(0).(model.Page)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PageRequest) error); ok {
		r1 = returnFunc(context1, pageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaces_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkspaces_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - pageRequest model.PageRequest
func (_e *MockWorkspaces_Expecter) List(context1 any, pageRequest any) *MockWorkspaces_List_Call {
	return &MockWorkspaces_List_Call{Call: _e.mock.On("List", context1, pageRequest)}
}

func (_c *MockWorkspaces_List_Call) Run(run func(context1 context.Context, pageRequest model.PageRequest)) *MockWorkspaces_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PageRequest
		if args[1] != nil {
			arg1 = args[1].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaces_List_Call) Return(page model.Page, err error) *MockWorkspaces_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockWorkspaces_List_Call) RunAndReturn(run func(context1 context.Context, pageRequest model.PageRequest) (model.Page, error)) *MockWorkspaces_List_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockWorkspaces
func (_mock *MockWorkspaces) Rename(context1 context.Context, s string, name model.Name, n int64) (model.Workspace, error) {
	ret := _mock.Called(context1, s, name, n)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 model.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Name, int64) (model.Workspace, error)); ok {
		return returnFunc(context1, s, name, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.Name, int64) model.Workspace); ok {
		r0 = returnFunc(context1, s, name, n)
	} else {
		r0 = ret.Get(0).(model.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.Name, int64) error); ok {
		r1 = returnFunc(context1, s, name, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaces_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockWorkspaces_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - name model.Name
//   - n int64
func (_e *MockWorkspaces_Expecter) Rename(context1 any, s any, name any, n any) *MockWorkspaces_Rename_Call {
	return &MockWorkspaces_Rename_Call{Call: _e.mock.On("Rename", context1, s, name, n)}
}

func (_c *MockWorkspaces_Rename_Call) Run(run func(context1 context.Context, s string, name model.Name, n int64)) *MockWorkspaces_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.Name
		if args[2] != nil {
			arg2 = args[2].(model.Name)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWorkspaces_Rename_Call) Return(workspace model.Workspace, err error) *MockWorkspaces_Rename_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockWorkspaces_Rename_Call) RunAndReturn(run func(context1 context.Context, s string, name model.Name, n int64) (model.Workspace, error)) *MockWorkspaces_Rename_Call {
	_c.Call.Return(run)
	return _c
}
