// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/chai-rs/handdraw-server/internal/document/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCodec creates a new instance of MockCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodec {
	mock := &MockCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodec is an autogenerated mock type for the Codec type
type MockCodec struct {
	mock.Mock
}

type MockCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodec) EXPECT() *MockCodec_Expecter {
	return &MockCodec_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockCodec
func (_mock *MockCodec) Apply(bytes []byte, bytes1 []byte, validation model.Validation) ([]byte, error) {
	ret := _mock.Called(bytes, bytes1, validation)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, model.Validation) ([]byte, error)); ok {
		return returnFunc(bytes, bytes1, validation)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, model.Validation) []byte); ok {
		r0 = returnFunc(bytes, bytes1, validation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte, model.Validation) error); ok {
		r1 = returnFunc(bytes, bytes1, validation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCodec_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockCodec_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - bytes []byte
//   - bytes1 []byte
//   - validation model.Validation
func (_e *MockCodec_Expecter) Apply(bytes any, bytes1 any, validation any) *MockCodec_Apply_Call {
	return &MockCodec_Apply_Call{Call: _e.mock.On("Apply", bytes, bytes1, validation)}
}

func (_c *MockCodec_Apply_Call) Run(run func(bytes []byte, bytes1 []byte, validation model.Validation)) *MockCodec_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 model.Validation
		if args[2] != nil {
			arg2 = args[2].(model.Validation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCodec_Apply_Call) Return(bytes2 []byte, err error) *MockCodec_Apply_Call {
	_c.Call.Return(bytes2, err)
	return _c
}

func (_c *MockCodec_Apply_Call) RunAndReturn(run func(bytes []byte, bytes1 []byte, validation model.Validation) ([]byte, error)) *MockCodec_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function for the type MockCodec
func (_mock *MockCodec) Decode(bytes []byte, validation model.Validation) (model.Snapshot, error) {
	ret := _mock.Called(bytes, validation)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 model.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, model.Validation) (model.Snapshot, error)); ok {
		return returnFunc(bytes, validation)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, model.Validation) model.Snapshot); ok {
		r0 = returnFunc(bytes, validation)
	} else {
		r0 = ret.Get(0).(model.Snapshot)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, model.Validation) error); ok {
		r1 = returnFunc(bytes, validation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCodec_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockCodec_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - bytes []byte
//   - validation model.Validation
func (_e *MockCodec_Expecter) Decode(bytes any, validation any) *MockCodec_Decode_Call {
	return &MockCodec_Decode_Call{Call: _e.mock.On("Decode", bytes, validation)}
}

func (_c *MockCodec_Decode_Call) Run(run func(bytes []byte, validation model.Validation)) *MockCodec_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 model.Validation
		if args[1] != nil {
			arg1 = args[1].(model.Validation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCodec_Decode_Call) Return(snapshot model.Snapshot, err error) *MockCodec_Decode_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockCodec_Decode_Call) RunAndReturn(run func(bytes []byte, validation model.Validation) (model.Snapshot, error)) *MockCodec_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type MockCodec
func (_mock *MockCodec) Encode(snapshot model.Snapshot, validation model.Validation) ([]byte, error) {
	ret := _mock.Called(snapshot, validation)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Snapshot, model.Validation) ([]byte, error)); ok {
		return returnFunc(snapshot, validation)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Snapshot, model.Validation) []byte); ok {
		r0 = returnFunc(snapshot, validation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.Snapshot, model.Validation) error); ok {
		r1 = returnFunc(snapshot, validation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCodec_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockCodec_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - snapshot model.Snapshot
//   - validation model.Validation
func (_e *MockCodec_Expecter) Encode(snapshot any, validation any) *MockCodec_Encode_Call {
	return &MockCodec_Encode_Call{Call: _e.mock.On("Encode", snapshot, validation)}
}

func (_c *MockCodec_Encode_Call) Run(run func(snapshot model.Snapshot, validation model.Validation)) *MockCodec_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Snapshot
		if args[0] != nil {
			arg0 = args[0].(model.Snapshot)
		}
		var arg1 model.Validation
		if args[1] != nil {
			arg1 = args[1].(model.Validation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCodec_Encode_Call) Return(bytes []byte, err error) *MockCodec_Encode_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCodec_Encode_Call) RunAndReturn(run func(snapshot model.Snapshot, validation model.Validation) ([]byte, error)) *MockCodec_Encode_Call {
	_c.Call.Return(run)
	return _c
}
