// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/transfer/model"
	model0 "github.com/chai-rs/handdraw-server/internal/asset/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type MockRepository
func (_mock *MockRepository) Complete(context1 context.Context, task model.Task, bytes []byte) error {
	ret := _mock.Called(context1, task, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task, []byte) error); ok {
		r0 = returnFunc(context1, task, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockRepository_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - context1 context.Context
//   - task model.Task
//   - bytes []byte
func (_e *MockRepository_Expecter) Complete(context1 any, task any, bytes any) *MockRepository_Complete_Call {
	return &MockRepository_Complete_Call{Call: _e.mock.On("Complete", context1, task, bytes)}
}

func (_c *MockRepository_Complete_Call) Run(run func(context1 context.Context, task model.Task, bytes []byte)) *MockRepository_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Task
		if args[1] != nil {
			arg1 = args[1].(model.Task)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Complete_Call) Return(err error) *MockRepository_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Complete_Call) RunAndReturn(run func(context1 context.Context, task model.Task, bytes []byte) error) *MockRepository_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type MockRepository
func (_mock *MockRepository) Enqueue(context1 context.Context, s string, s1 string, s2 string, s3 string, s4 string, b bool) error {
	ret := _mock.Called(context1, s, s1, s2, s3, s4, b)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, bool) error); ok {
		r0 = returnFunc(context1, s, s1, s2, s3, s4, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockRepository_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - s3 string
//   - s4 string
//   - b bool
func (_e *MockRepository_Expecter) Enqueue(context1 any, s any, s1 any, s2 any, s3 any, s4 any, b any) *MockRepository_Enqueue_Call {
	return &MockRepository_Enqueue_Call{Call: _e.mock.On("Enqueue", context1, s, s1, s2, s3, s4, b)}
}

func (_c *MockRepository_Enqueue_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, s4 string, b bool)) *MockRepository_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockRepository_Enqueue_Call) Return(err error) *MockRepository_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Enqueue_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, s4 string, b bool) error) *MockRepository_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function for the type MockRepository
func (_mock *MockRepository) Fail(context1 context.Context, task model.Task, s string) error {
	ret := _mock.Called(context1, task, s)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task, string) error); ok {
		r0 = returnFunc(context1, task, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type MockRepository_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - context1 context.Context
//   - task model.Task
//   - s string
func (_e *MockRepository_Expecter) Fail(context1 any, task any, s any) *MockRepository_Fail_Call {
	return &MockRepository_Fail_Call{Call: _e.mock.On("Fail", context1, task, s)}
}

func (_c *MockRepository_Fail_Call) Run(run func(context1 context.Context, task model.Task, s string)) *MockRepository_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Task
		if args[1] != nil {
			arg1 = args[1].(model.Task)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Fail_Call) Return(err error) *MockRepository_Fail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Fail_Call) RunAndReturn(run func(context1 context.Context, task model.Task, s string) error) *MockRepository_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(context1 context.Context, s string) (model.Job, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Job, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Job); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Get(context1 any, s any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *MockRepository_Get_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(job model.Job, err error) *MockRepository_Get_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Job, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Lease provides a mock function for the type MockRepository
func (_mock *MockRepository) Lease(context1 context.Context, s string) (model.Task, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Lease")
	}

	var r0 model.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Task, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Task); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Lease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lease'
type MockRepository_Lease_Call struct {
	*mock.Call
}

// Lease is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Lease(context1 any, s any) *MockRepository_Lease_Call {
	return &MockRepository_Lease_Call{Call: _e.mock.On("Lease", context1, s)}
}

func (_c *MockRepository_Lease_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Lease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Lease_Call) Return(task model.Task, err error) *MockRepository_Lease_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockRepository_Lease_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Task, error)) *MockRepository_Lease_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type MockRepository
func (_mock *MockRepository) Prepare(context1 context.Context, task model.Task, assets []model0.Asset) error {
	ret := _mock.Called(context1, task, assets)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task, []model0.Asset) error); ok {
		r0 = returnFunc(context1, task, assets)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockRepository_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - context1 context.Context
//   - task model.Task
//   - assets []model0.Asset
func (_e *MockRepository_Expecter) Prepare(context1 any, task any, assets any) *MockRepository_Prepare_Call {
	return &MockRepository_Prepare_Call{Call: _e.mock.On("Prepare", context1, task, assets)}
}

func (_c *MockRepository_Prepare_Call) Run(run func(context1 context.Context, task model.Task, assets []model0.Asset)) *MockRepository_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Task
		if args[1] != nil {
			arg1 = args[1].(model.Task)
		}
		var arg2 []model0.Asset
		if args[2] != nil {
			arg2 = args[2].([]model0.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Prepare_Call) Return(err error) *MockRepository_Prepare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Prepare_Call) RunAndReturn(run func(context1 context.Context, task model.Task, assets []model0.Asset) error) *MockRepository_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockRepository
func (_mock *MockRepository) Run(context1 context.Context, task model.Task, fn func(context.Context, model.Payload) error) error {
	ret := _mock.Called(context1, task, fn)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Task, func(context.Context, model.Payload) error) error); ok {
		r0 = returnFunc(context1, task, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRepository_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
//   - task model.Task
//   - fn func(context.Context, model.Payload) error
func (_e *MockRepository_Expecter) Run(context1 any, task any, fn any) *MockRepository_Run_Call {
	return &MockRepository_Run_Call{Call: _e.mock.On("Run", context1, task, fn)}
}

func (_c *MockRepository_Run_Call) Run(run func(context1 context.Context, task model.Task, fn func(context.Context, model.Payload) error)) *MockRepository_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Task
		if args[1] != nil {
			arg1 = args[1].(model.Task)
		}
		var arg2 func(context.Context, model.Payload) error
		if args[2] != nil {
			arg2 = args[2].(func(context.Context, model.Payload) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Run_Call) Return(err error) *MockRepository_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Run_Call) RunAndReturn(run func(context1 context.Context, task model.Task, fn func(context.Context, model.Payload) error) error) *MockRepository_Run_Call {
	_c.Call.Return(run)
	return _c
}
