// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/asset/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Finalize provides a mock function for the type MockStorage
func (_mock *MockStorage) Finalize(context1 context.Context, asset model.Asset) error {
	ret := _mock.Called(context1, asset)

	if len(ret) == 0 {
		panic("no return value specified for Finalize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Asset) error); ok {
		r0 = returnFunc(context1, asset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type MockStorage_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
//   - context1 context.Context
//   - asset model.Asset
func (_e *MockStorage_Expecter) Finalize(context1 any, asset any) *MockStorage_Finalize_Call {
	return &MockStorage_Finalize_Call{Call: _e.mock.On("Finalize", context1, asset)}
}

func (_c *MockStorage_Finalize_Call) Run(run func(context1 context.Context, asset model.Asset)) *MockStorage_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Asset
		if args[1] != nil {
			arg1 = args[1].(model.Asset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Finalize_Call) Return(err error) *MockStorage_Finalize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Finalize_Call) RunAndReturn(run func(context1 context.Context, asset model.Asset) error) *MockStorage_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockStorage
func (_mock *MockStorage) Read(context1 context.Context, asset model.Asset) ([]byte, error) {
	ret := _mock.Called(context1, asset)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Asset) ([]byte, error)); ok {
		return returnFunc(context1, asset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Asset) []byte); ok {
		r0 = returnFunc(context1, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Asset) error); ok {
		r1 = returnFunc(context1, asset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockStorage_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - context1 context.Context
//   - asset model.Asset
func (_e *MockStorage_Expecter) Read(context1 any, asset any) *MockStorage_Read_Call {
	return &MockStorage_Read_Call{Call: _e.mock.On("Read", context1, asset)}
}

func (_c *MockStorage_Read_Call) Run(run func(context1 context.Context, asset model.Asset)) *MockStorage_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Asset
		if args[1] != nil {
			arg1 = args[1].(model.Asset)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Read_Call) Return(bytes []byte, err error) *MockStorage_Read_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockStorage_Read_Call) RunAndReturn(run func(context1 context.Context, asset model.Asset) ([]byte, error)) *MockStorage_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockStorage
func (_mock *MockStorage) Remove(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockStorage_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStorage_Expecter) Remove(context1 any, s any) *MockStorage_Remove_Call {
	return &MockStorage_Remove_Call{Call: _e.mock.On("Remove", context1, s)}
}

func (_c *MockStorage_Remove_Call) Run(run func(context1 context.Context, s string)) *MockStorage_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Remove_Call) Return(err error) *MockStorage_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Remove_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockStorage_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Stage provides a mock function for the type MockStorage
func (_mock *MockStorage) Stage(context1 context.Context, asset model.Asset, bytes []byte) error {
	ret := _mock.Called(context1, asset, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Stage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Asset, []byte) error); ok {
		r0 = returnFunc(context1, asset, bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Stage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stage'
type MockStorage_Stage_Call struct {
	*mock.Call
}

// Stage is a helper method to define mock.On call
//   - context1 context.Context
//   - asset model.Asset
//   - bytes []byte
func (_e *MockStorage_Expecter) Stage(context1 any, asset any, bytes any) *MockStorage_Stage_Call {
	return &MockStorage_Stage_Call{Call: _e.mock.On("Stage", context1, asset, bytes)}
}

func (_c *MockStorage_Stage_Call) Run(run func(context1 context.Context, asset model.Asset, bytes []byte)) *MockStorage_Stage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Asset
		if args[1] != nil {
			arg1 = args[1].(model.Asset)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Stage_Call) Return(err error) *MockStorage_Stage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Stage_Call) RunAndReturn(run func(context1 context.Context, asset model.Asset, bytes []byte) error) *MockStorage_Stage_Call {
	_c.Call.Return(run)
	return _c
}
