// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/board/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBoardRepository creates a new instance of MockBoardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoardRepository {
	mock := &MockBoardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoardRepository is an autogenerated mock type for the BoardRepository type
type MockBoardRepository struct {
	mock.Mock
}

type MockBoardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoardRepository) EXPECT() *MockBoardRepository_Expecter {
	return &MockBoardRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBoardRepository
func (_mock *MockBoardRepository) Create(context1 context.Context, board model.Board, initialDocument model.InitialDocument) (model.Board, error) {
	ret := _mock.Called(context1, board, initialDocument)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Board, model.InitialDocument) (model.Board, error)); ok {
		return returnFunc(context1, board, initialDocument)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Board, model.InitialDocument) model.Board); ok {
		r0 = returnFunc(context1, board, initialDocument)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Board, model.InitialDocument) error); ok {
		r1 = returnFunc(context1, board, initialDocument)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBoardRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - board model.Board
//   - initialDocument model.InitialDocument
func (_e *MockBoardRepository_Expecter) Create(context1 any, board any, initialDocument any) *MockBoardRepository_Create_Call {
	return &MockBoardRepository_Create_Call{Call: _e.mock.On("Create", context1, board, initialDocument)}
}

func (_c *MockBoardRepository_Create_Call) Run(run func(context1 context.Context, board model.Board, initialDocument model.InitialDocument)) *MockBoardRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Board
		if args[1] != nil {
			arg1 = args[1].(model.Board)
		}
		var arg2 model.InitialDocument
		if args[2] != nil {
			arg2 = args[2].(model.InitialDocument)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoardRepository_Create_Call) Return(board1 model.Board, err error) *MockBoardRepository_Create_Call {
	_c.Call.Return(board1, err)
	return _c
}

func (_c *MockBoardRepository_Create_Call) RunAndReturn(run func(context1 context.Context, board model.Board, initialDocument model.InitialDocument) (model.Board, error)) *MockBoardRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBoardRepository
func (_mock *MockBoardRepository) Get(context1 context.Context, s string, s1 string) (model.Board, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Board, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Board); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBoardRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockBoardRepository_Expecter) Get(context1 any, s any, s1 any) *MockBoardRepository_Get_Call {
	return &MockBoardRepository_Get_Call{Call: _e.mock.On("Get", context1, s, s1)}
}

func (_c *MockBoardRepository_Get_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockBoardRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoardRepository_Get_Call) Return(board model.Board, err error) *MockBoardRepository_Get_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockBoardRepository_Get_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (model.Board, error)) *MockBoardRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBoardRepository
func (_mock *MockBoardRepository) List(context1 context.Context, s string, s1 *string, pageRequest model.PageRequest) (model.Page[model.Board], error) {
	ret := _mock.Called(context1, s, s1, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Page[model.Board]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, model.PageRequest) (model.Page[model.Board], error)); ok {
		return returnFunc(context1, s, s1, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, model.PageRequest) model.Page[model.Board]); ok {
		r0 = returnFunc(context1, s, s1, pageRequest)
	} else {
		r0 = ret.Get(0).(model.Page[model.Board])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, model.PageRequest) error); ok {
		r1 = returnFunc(context1, s, s1, pageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBoardRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 *string
//   - pageRequest model.PageRequest
func (_e *MockBoardRepository_Expecter) List(context1 any, s any, s1 any, pageRequest any) *MockBoardRepository_List_Call {
	return &MockBoardRepository_List_Call{Call: _e.mock.On("List", context1, s, s1, pageRequest)}
}

func (_c *MockBoardRepository_List_Call) Run(run func(context1 context.Context, s string, s1 *string, pageRequest model.PageRequest)) *MockBoardRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 model.PageRequest
		if args[3] != nil {
			arg3 = args[3].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBoardRepository_List_Call) Return(page model.Page[model.Board], err error) *MockBoardRepository_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockBoardRepository_List_Call) RunAndReturn(run func(context1 context.Context, s string, s1 *string, pageRequest model.PageRequest) (model.Page[model.Board], error)) *MockBoardRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDeleting provides a mock function for the type MockBoardRepository
func (_mock *MockBoardRepository) MarkDeleting(context1 context.Context, s string, s1 string, n int64) (model.Board, error) {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for MarkDeleting")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (model.Board, error)); ok {
		return returnFunc(context1, s, s1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) model.Board); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(context1, s, s1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardRepository_MarkDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDeleting'
type MockBoardRepository_MarkDeleting_Call struct {
	*mock.Call
}

// MarkDeleting is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int64
func (_e *MockBoardRepository_Expecter) MarkDeleting(context1 any, s any, s1 any, n any) *MockBoardRepository_MarkDeleting_Call {
	return &MockBoardRepository_MarkDeleting_Call{Call: _e.mock.On("MarkDeleting", context1, s, s1, n)}
}

func (_c *MockBoardRepository_MarkDeleting_Call) Run(run func(context1 context.Context, s string, s1 string, n int64)) *MockBoardRepository_MarkDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBoardRepository_MarkDeleting_Call) Return(board model.Board, err error) *MockBoardRepository_MarkDeleting_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockBoardRepository_MarkDeleting_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int64) (model.Board, error)) *MockBoardRepository_MarkDeleting_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBoardRepository
func (_mock *MockBoardRepository) Update(context1 context.Context, s string, s1 string, boardPatch model.BoardPatch, n int64) (model.Board, error) {
	ret := _mock.Called(context1, s, s1, boardPatch, n)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.BoardPatch, int64) (model.Board, error)); ok {
		return returnFunc(context1, s, s1, boardPatch, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.BoardPatch, int64) model.Board); ok {
		r0 = returnFunc(context1, s, s1, boardPatch, n)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, model.BoardPatch, int64) error); ok {
		r1 = returnFunc(context1, s, s1, boardPatch, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBoardRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - boardPatch model.BoardPatch
//   - n int64
func (_e *MockBoardRepository_Expecter) Update(context1 any, s any, s1 any, boardPatch any, n any) *MockBoardRepository_Update_Call {
	return &MockBoardRepository_Update_Call{Call: _e.mock.On("Update", context1, s, s1, boardPatch, n)}
}

func (_c *MockBoardRepository_Update_Call) Run(run func(context1 context.Context, s string, s1 string, boardPatch model.BoardPatch, n int64)) *MockBoardRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.BoardPatch
		if args[3] != nil {
			arg3 = args[3].(model.BoardPatch)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBoardRepository_Update_Call) Return(board model.Board, err error) *MockBoardRepository_Update_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockBoardRepository_Update_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, boardPatch model.BoardPatch, n int64) (model.Board, error)) *MockBoardRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
