// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/board/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Create(context1 context.Context, project model.Project) (model.Project, error) {
	ret := _mock.Called(context1, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Project) (model.Project, error)); ok {
		return returnFunc(context1, project)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Project) model.Project); ok {
		r0 = returnFunc(context1, project)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Project) error); ok {
		r1 = returnFunc(context1, project)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - project model.Project
func (_e *MockProjectRepository_Expecter) Create(context1 any, project any) *MockProjectRepository_Create_Call {
	return &MockProjectRepository_Create_Call{Call: _e.mock.On("Create", context1, project)}
}

func (_c *MockProjectRepository_Create_Call) Run(run func(context1 context.Context, project model.Project)) *MockProjectRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Project
		if args[1] != nil {
			arg1 = args[1].(model.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Create_Call) Return(project1 model.Project, err error) *MockProjectRepository_Create_Call {
	_c.Call.Return(project1, err)
	return _c
}

func (_c *MockProjectRepository_Create_Call) RunAndReturn(run func(context1 context.Context, project model.Project) (model.Project, error)) *MockProjectRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEmpty provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) DeleteEmpty(context1 context.Context, s string, s1 string, n int64) error {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmpty")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_DeleteEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEmpty'
type MockProjectRepository_DeleteEmpty_Call struct {
	*mock.Call
}

// DeleteEmpty is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int64
func (_e *MockProjectRepository_Expecter) DeleteEmpty(context1 any, s any, s1 any, n any) *MockProjectRepository_DeleteEmpty_Call {
	return &MockProjectRepository_DeleteEmpty_Call{Call: _e.mock.On("DeleteEmpty", context1, s, s1, n)}
}

func (_c *MockProjectRepository_DeleteEmpty_Call) Run(run func(context1 context.Context, s string, s1 string, n int64)) *MockProjectRepository_DeleteEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProjectRepository_DeleteEmpty_Call) Return(err error) *MockProjectRepository_DeleteEmpty_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_DeleteEmpty_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int64) error) *MockProjectRepository_DeleteEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Get(context1 context.Context, s string, s1 string) (model.Project, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Project, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Project); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProjectRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockProjectRepository_Expecter) Get(context1 any, s any, s1 any) *MockProjectRepository_Get_Call {
	return &MockProjectRepository_Get_Call{Call: _e.mock.On("Get", context1, s, s1)}
}

func (_c *MockProjectRepository_Get_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockProjectRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Get_Call) Return(project model.Project, err error) *MockProjectRepository_Get_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectRepository_Get_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (model.Project, error)) *MockProjectRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) List(context1 context.Context, s string, pageRequest model.PageRequest) (model.Page[model.Project], error) {
	ret := _mock.Called(context1, s, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Page[model.Project]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PageRequest) (model.Page[model.Project], error)); ok {
		return returnFunc(context1, s, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PageRequest) model.Page[model.Project]); ok {
		r0 = returnFunc(context1, s, pageRequest)
	} else {
		r0 = ret.Get(0).(model.Page[model.Project])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.PageRequest) error); ok {
		r1 = returnFunc(context1, s, pageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProjectRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - pageRequest model.PageRequest
func (_e *MockProjectRepository_Expecter) List(context1 any, s any, pageRequest any) *MockProjectRepository_List_Call {
	return &MockProjectRepository_List_Call{Call: _e.mock.On("List", context1, s, pageRequest)}
}

func (_c *MockProjectRepository_List_Call) Run(run func(context1 context.Context, s string, pageRequest model.PageRequest)) *MockProjectRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.PageRequest
		if args[2] != nil {
			arg2 = args[2].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProjectRepository_List_Call) Return(page model.Page[model.Project], err error) *MockProjectRepository_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockProjectRepository_List_Call) RunAndReturn(run func(context1 context.Context, s string, pageRequest model.PageRequest) (model.Page[model.Project], error)) *MockProjectRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Rename(context1 context.Context, s string, s1 string, s2 string, n int64) (model.Project, error) {
	ret := _mock.Called(context1, s, s1, s2, n)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (model.Project, error)); ok {
		return returnFunc(context1, s, s1, s2, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) model.Project); ok {
		r0 = returnFunc(context1, s, s1, s2, n)
	} else {
		r0 = ret.Get(0).(model.Project)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = returnFunc(context1, s, s1, s2, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockProjectRepository_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - n int64
func (_e *MockProjectRepository_Expecter) Rename(context1 any, s any, s1 any, s2 any, n any) *MockProjectRepository_Rename_Call {
	return &MockProjectRepository_Rename_Call{Call: _e.mock.On("Rename", context1, s, s1, s2, n)}
}

func (_c *MockProjectRepository_Rename_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, n int64)) *MockProjectRepository_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Rename_Call) Return(project model.Project, err error) *MockProjectRepository_Rename_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectRepository_Rename_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, n int64) (model.Project, error)) *MockProjectRepository_Rename_Call {
	_c.Call.Return(run)
	return _c
}
