// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/access/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccess creates a new instance of MockAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccess {
	mock := &MockAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccess is an autogenerated mock type for the Access type
type MockAccess struct {
	mock.Mock
}

type MockAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccess) EXPECT() *MockAccess_Expecter {
	return &MockAccess_Expecter{mock: &_m.Mock}
}

// Require provides a mock function for the type MockAccess
func (_mock *MockAccess) Require(context1 context.Context, target model.Target, action model.Action) (model.Decision, error) {
	ret := _mock.Called(context1, target, action)

	if len(ret) == 0 {
		panic("no return value specified for Require")
	}

	var r0 model.Decision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Target, model.Action) (model.Decision, error)); ok {
		return returnFunc(context1, target, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Target, model.Action) model.Decision); ok {
		r0 = returnFunc(context1, target, action)
	} else {
		r0 = ret.Get(0).(model.Decision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Target, model.Action) error); ok {
		r1 = returnFunc(context1, target, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccess_Require_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Require'
type MockAccess_Require_Call struct {
	*mock.Call
}

// Require is a helper method to define mock.On call
//   - context1 context.Context
//   - target model.Target
//   - action model.Action
func (_e *MockAccess_Expecter) Require(context1 any, target any, action any) *MockAccess_Require_Call {
	return &MockAccess_Require_Call{Call: _e.mock.On("Require", context1, target, action)}
}

func (_c *MockAccess_Require_Call) Run(run func(context1 context.Context, target model.Target, action model.Action)) *MockAccess_Require_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Target
		if args[1] != nil {
			arg1 = args[1].(model.Target)
		}
		var arg2 model.Action
		if args[2] != nil {
			arg2 = args[2].(model.Action)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccess_Require_Call) Return(decision model.Decision, err error) *MockAccess_Require_Call {
	_c.Call.Return(decision, err)
	return _c
}

func (_c *MockAccess_Require_Call) RunAndReturn(run func(context1 context.Context, target model.Target, action model.Action) (model.Decision, error)) *MockAccess_Require_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockAccess
func (_mock *MockAccess) Resolve(context1 context.Context, target model.Target) (model.Decision, error) {
	ret := _mock.Called(context1, target)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 model.Decision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Target) (model.Decision, error)); ok {
		return returnFunc(context1, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Target) model.Decision); ok {
		r0 = returnFunc(context1, target)
	} else {
		r0 = ret.Get(0).(model.Decision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Target) error); ok {
		r1 = returnFunc(context1, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccess_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockAccess_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - context1 context.Context
//   - target model.Target
func (_e *MockAccess_Expecter) Resolve(context1 any, target any) *MockAccess_Resolve_Call {
	return &MockAccess_Resolve_Call{Call: _e.mock.On("Resolve", context1, target)}
}

func (_c *MockAccess_Resolve_Call) Run(run func(context1 context.Context, target model.Target)) *MockAccess_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Target
		if args[1] != nil {
			arg1 = args[1].(model.Target)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccess_Resolve_Call) Return(decision model.Decision, err error) *MockAccess_Resolve_Call {
	_c.Call.Return(decision, err)
	return _c
}

func (_c *MockAccess_Resolve_Call) RunAndReturn(run func(context1 context.Context, target model.Target) (model.Decision, error)) *MockAccess_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
