// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/board/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBoards creates a new instance of MockBoards. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoards(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoards {
	mock := &MockBoards{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoards is an autogenerated mock type for the Boards type
type MockBoards struct {
	mock.Mock
}

type MockBoards_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoards) EXPECT() *MockBoards_Expecter {
	return &MockBoards_Expecter{mock: &_m.Mock}
}

// CreatePrepared provides a mock function for the type MockBoards
func (_mock *MockBoards) CreatePrepared(context1 context.Context, board model.Board, initialDocument model.InitialDocument) (model.Board, error) {
	ret := _mock.Called(context1, board, initialDocument)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrepared")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Board, model.InitialDocument) (model.Board, error)); ok {
		return returnFunc(context1, board, initialDocument)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Board, model.InitialDocument) model.Board); ok {
		r0 = returnFunc(context1, board, initialDocument)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Board, model.InitialDocument) error); ok {
		r1 = returnFunc(context1, board, initialDocument)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoards_CreatePrepared_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrepared'
type MockBoards_CreatePrepared_Call struct {
	*mock.Call
}

// CreatePrepared is a helper method to define mock.On call
//   - context1 context.Context
//   - board model.Board
//   - initialDocument model.InitialDocument
func (_e *MockBoards_Expecter) CreatePrepared(context1 any, board any, initialDocument any) *MockBoards_CreatePrepared_Call {
	return &MockBoards_CreatePrepared_Call{Call: _e.mock.On("CreatePrepared", context1, board, initialDocument)}
}

func (_c *MockBoards_CreatePrepared_Call) Run(run func(context1 context.Context, board model.Board, initialDocument model.InitialDocument)) *MockBoards_CreatePrepared_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Board
		if args[1] != nil {
			arg1 = args[1].(model.Board)
		}
		var arg2 model.InitialDocument
		if args[2] != nil {
			arg2 = args[2].(model.InitialDocument)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoards_CreatePrepared_Call) Return(board1 model.Board, err error) *MockBoards_CreatePrepared_Call {
	_c.Call.Return(board1, err)
	return _c
}

func (_c *MockBoards_CreatePrepared_Call) RunAndReturn(run func(context1 context.Context, board model.Board, initialDocument model.InitialDocument) (model.Board, error)) *MockBoards_CreatePrepared_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBoards
func (_mock *MockBoards) Get(context1 context.Context, s string, s1 string) (model.Board, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Board, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Board); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoards_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBoards_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockBoards_Expecter) Get(context1 any, s any, s1 any) *MockBoards_Get_Call {
	return &MockBoards_Get_Call{Call: _e.mock.On("Get", context1, s, s1)}
}

func (_c *MockBoards_Get_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockBoards_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoards_Get_Call) Return(board model.Board, err error) *MockBoards_Get_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockBoards_Get_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (model.Board, error)) *MockBoards_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBoards
func (_mock *MockBoards) List(context1 context.Context, s string, s1 *string, pageRequest model.PageRequest) (model.Page[model.Board], error) {
	ret := _mock.Called(context1, s, s1, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 model.Page[model.Board]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, model.PageRequest) (model.Page[model.Board], error)); ok {
		return returnFunc(context1, s, s1, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, model.PageRequest) model.Page[model.Board]); ok {
		r0 = returnFunc(context1, s, s1, pageRequest)
	} else {
		r0 = ret.Get(0).(model.Page[model.Board])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, model.PageRequest) error); ok {
		r1 = returnFunc(context1, s, s1, pageRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoards_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBoards_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 *string
//   - pageRequest model.PageRequest
func (_e *MockBoards_Expecter) List(context1 any, s any, s1 any, pageRequest any) *MockBoards_List_Call {
	return &MockBoards_List_Call{Call: _e.mock.On("List", context1, s, s1, pageRequest)}
}

func (_c *MockBoards_List_Call) Run(run func(context1 context.Context, s string, s1 *string, pageRequest model.PageRequest)) *MockBoards_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 model.PageRequest
		if args[3] != nil {
			arg3 = args[3].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBoards_List_Call) Return(page model.Page[model.Board], err error) *MockBoards_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *MockBoards_List_Call) RunAndReturn(run func(context1 context.Context, s string, s1 *string, pageRequest model.PageRequest) (model.Page[model.Board], error)) *MockBoards_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDeleting provides a mock function for the type MockBoards
func (_mock *MockBoards) MarkDeleting(context1 context.Context, s string, s1 string, n int64) (model.Board, error) {
	ret := _mock.Called(context1, s, s1, n)

	if len(ret) == 0 {
		panic("no return value specified for MarkDeleting")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (model.Board, error)); ok {
		return returnFunc(context1, s, s1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) model.Board); ok {
		r0 = returnFunc(context1, s, s1, n)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(context1, s, s1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoards_MarkDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDeleting'
type MockBoards_MarkDeleting_Call struct {
	*mock.Call
}

// MarkDeleting is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - n int64
func (_e *MockBoards_Expecter) MarkDeleting(context1 any, s any, s1 any, n any) *MockBoards_MarkDeleting_Call {
	return &MockBoards_MarkDeleting_Call{Call: _e.mock.On("MarkDeleting", context1, s, s1, n)}
}

func (_c *MockBoards_MarkDeleting_Call) Run(run func(context1 context.Context, s string, s1 string, n int64)) *MockBoards_MarkDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBoards_MarkDeleting_Call) Return(board model.Board, err error) *MockBoards_MarkDeleting_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockBoards_MarkDeleting_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, n int64) (model.Board, error)) *MockBoards_MarkDeleting_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBoards
func (_mock *MockBoards) Update(context1 context.Context, s string, s1 string, boardPatch model.BoardPatch, n int64) (model.Board, error) {
	ret := _mock.Called(context1, s, s1, boardPatch, n)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.BoardPatch, int64) (model.Board, error)); ok {
		return returnFunc(context1, s, s1, boardPatch, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.BoardPatch, int64) model.Board); ok {
		r0 = returnFunc(context1, s, s1, boardPatch, n)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, model.BoardPatch, int64) error); ok {
		r1 = returnFunc(context1, s, s1, boardPatch, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoards_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBoards_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - boardPatch model.BoardPatch
//   - n int64
func (_e *MockBoards_Expecter) Update(context1 any, s any, s1 any, boardPatch any, n any) *MockBoards_Update_Call {
	return &MockBoards_Update_Call{Call: _e.mock.On("Update", context1, s, s1, boardPatch, n)}
}

func (_c *MockBoards_Update_Call) Run(run func(context1 context.Context, s string, s1 string, boardPatch model.BoardPatch, n int64)) *MockBoards_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.BoardPatch
		if args[3] != nil {
			arg3 = args[3].(model.BoardPatch)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBoards_Update_Call) Return(board model.Board, err error) *MockBoards_Update_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockBoards_Update_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, boardPatch model.BoardPatch, n int64) (model.Board, error)) *MockBoards_Update_Call {
	_c.Call.Return(run)
	return _c
}
