// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/chai-rs/handdraw-server/internal/document/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBuilder creates a new instance of MockBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBuilder {
	mock := &MockBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBuilder is an autogenerated mock type for the Builder type
type MockBuilder struct {
	mock.Mock
}

type MockBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBuilder) EXPECT() *MockBuilder_Expecter {
	return &MockBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockBuilder
func (_mock *MockBuilder) Build(s string, s1 string) (service.InitialDocument, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 service.InitialDocument
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (service.InitialDocument, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) service.InitialDocument); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Get(0).(service.InitialDocument)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockBuilder_Expecter) Build(s any, s1 any) *MockBuilder_Build_Call {
	return &MockBuilder_Build_Call{Call: _e.mock.On("Build", s, s1)}
}

func (_c *MockBuilder_Build_Call) Run(run func(s string, s1 string)) *MockBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBuilder_Build_Call) Return(initialDocument service.InitialDocument, err error) *MockBuilder_Build_Call {
	_c.Call.Return(initialDocument, err)
	return _c
}

func (_c *MockBuilder_Build_Call) RunAndReturn(run func(s string, s1 string) (service.InitialDocument, error)) *MockBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
