// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/board_management/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuery creates a new instance of MockQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuery {
	mock := &MockQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuery is an autogenerated mock type for the Query type
type MockQuery struct {
	mock.Mock
}

type MockQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuery) EXPECT() *MockQuery_Expecter {
	return &MockQuery_Expecter{mock: &_m.Mock}
}

// Document provides a mock function for the type MockQuery
func (_mock *MockQuery) Document(context1 context.Context, s string) ([]byte, int, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Document")
	}

	var r0 []byte
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, int, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(context1, s)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQuery_Document_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Document'
type MockQuery_Document_Call struct {
	*mock.Call
}

// Document is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockQuery_Expecter) Document(context1 any, s any) *MockQuery_Document_Call {
	return &MockQuery_Document_Call{Call: _e.mock.On("Document", context1, s)}
}

func (_c *MockQuery_Document_Call) Run(run func(context1 context.Context, s string)) *MockQuery_Document_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuery_Document_Call) Return(bytes []byte, n int, err error) *MockQuery_Document_Call {
	_c.Call.Return(bytes, n, err)
	return _c
}

func (_c *MockQuery_Document_Call) RunAndReturn(run func(context1 context.Context, s string) ([]byte, int, error)) *MockQuery_Document_Call {
	_c.Call.Return(run)
	return _c
}

// LockWorkspace provides a mock function for the type MockQuery
func (_mock *MockQuery) LockWorkspace(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for LockWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuery_LockWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockWorkspace'
type MockQuery_LockWorkspace_Call struct {
	*mock.Call
}

// LockWorkspace is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockQuery_Expecter) LockWorkspace(context1 any, s any) *MockQuery_LockWorkspace_Call {
	return &MockQuery_LockWorkspace_Call{Call: _e.mock.On("LockWorkspace", context1, s)}
}

func (_c *MockQuery_LockWorkspace_Call) Run(run func(context1 context.Context, s string)) *MockQuery_LockWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuery_LockWorkspace_Call) Return(err error) *MockQuery_LockWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuery_LockWorkspace_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockQuery_LockWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectScope provides a mock function for the type MockQuery
func (_mock *MockQuery) ProjectScope(context1 context.Context, s string) (model.ProjectScope, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ProjectScope")
	}

	var r0 model.ProjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.ProjectScope, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.ProjectScope); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.ProjectScope)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuery_ProjectScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectScope'
type MockQuery_ProjectScope_Call struct {
	*mock.Call
}

// ProjectScope is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockQuery_Expecter) ProjectScope(context1 any, s any) *MockQuery_ProjectScope_Call {
	return &MockQuery_ProjectScope_Call{Call: _e.mock.On("ProjectScope", context1, s)}
}

func (_c *MockQuery_ProjectScope_Call) Run(run func(context1 context.Context, s string)) *MockQuery_ProjectScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuery_ProjectScope_Call) Return(projectScope model.ProjectScope, err error) *MockQuery_ProjectScope_Call {
	_c.Call.Return(projectScope, err)
	return _c
}

func (_c *MockQuery_ProjectScope_Call) RunAndReturn(run func(context1 context.Context, s string) (model.ProjectScope, error)) *MockQuery_ProjectScope_Call {
	_c.Call.Return(run)
	return _c
}

// SchemaVersion provides a mock function for the type MockQuery
func (_mock *MockQuery) SchemaVersion(context1 context.Context, s string) (int, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for SchemaVersion")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuery_SchemaVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchemaVersion'
type MockQuery_SchemaVersion_Call struct {
	*mock.Call
}

// SchemaVersion is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockQuery_Expecter) SchemaVersion(context1 any, s any) *MockQuery_SchemaVersion_Call {
	return &MockQuery_SchemaVersion_Call{Call: _e.mock.On("SchemaVersion", context1, s)}
}

func (_c *MockQuery_SchemaVersion_Call) Run(run func(context1 context.Context, s string)) *MockQuery_SchemaVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuery_SchemaVersion_Call) Return(n int, err error) *MockQuery_SchemaVersion_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuery_SchemaVersion_Call) RunAndReturn(run func(context1 context.Context, s string) (int, error)) *MockQuery_SchemaVersion_Call {
	_c.Call.Return(run)
	return _c
}
