// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/identity/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Authenticate(context1 context.Context, accessToken model.AccessToken) (model.Principal, error) {
	ret := _mock.Called(context1, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 model.Principal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AccessToken) (model.Principal, error)); ok {
		return returnFunc(context1, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AccessToken) model.Principal); ok {
		r0 = returnFunc(context1, accessToken)
	} else {
		r0 = ret.Get(0).(model.Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.AccessToken) error); ok {
		r1 = returnFunc(context1, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - context1 context.Context
//   - accessToken model.AccessToken
func (_e *MockAuthenticator_Expecter) Authenticate(context1 any, accessToken any) *MockAuthenticator_Authenticate_Call {
	return &MockAuthenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", context1, accessToken)}
}

func (_c *MockAuthenticator_Authenticate_Call) Run(run func(context1 context.Context, accessToken model.AccessToken)) *MockAuthenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AccessToken
		if args[1] != nil {
			arg1 = args[1].(model.AccessToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call) Return(principal model.Principal, err error) *MockAuthenticator_Authenticate_Call {
	_c.Call.Return(principal, err)
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call) RunAndReturn(run func(context1 context.Context, accessToken model.AccessToken) (model.Principal, error)) *MockAuthenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}
