// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/access/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockRepository
func (_mock *MockRepository) Load(context1 context.Context, target model.Target) (model.Facts, error) {
	ret := _mock.Called(context1, target)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 model.Facts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Target) (model.Facts, error)); ok {
		return returnFunc(context1, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Target) model.Facts); ok {
		r0 = returnFunc(context1, target)
	} else {
		r0 = ret.Get(0).(model.Facts)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Target) error); ok {
		r1 = returnFunc(context1, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - context1 context.Context
//   - target model.Target
func (_e *MockRepository_Expecter) Load(context1 any, target any) *MockRepository_Load_Call {
	return &MockRepository_Load_Call{Call: _e.mock.On("Load", context1, target)}
}

func (_c *MockRepository_Load_Call) Run(run func(context1 context.Context, target model.Target)) *MockRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Target
		if args[1] != nil {
			arg1 = args[1].(model.Target)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Load_Call) Return(facts model.Facts, err error) *MockRepository_Load_Call {
	_c.Call.Return(facts, err)
	return _c
}

func (_c *MockRepository_Load_Call) RunAndReturn(run func(context1 context.Context, target model.Target) (model.Facts, error)) *MockRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}
