// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactions creates a new instance of MockTransactions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactions {
	mock := &MockTransactions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactions is an autogenerated mock type for the Transactions type
type MockTransactions struct {
	mock.Mock
}

type MockTransactions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactions) EXPECT() *MockTransactions_Expecter {
	return &MockTransactions_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTransactions
func (_mock *MockTransactions) Run(context1 context.Context, s string, fn func(context.Context) error) error {
	ret := _mock.Called(context1, s, fn)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) error); ok {
		r0 = returnFunc(context1, s, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactions_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTransactions_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - fn func(context.Context) error
func (_e *MockTransactions_Expecter) Run(context1 any, s any, fn any) *MockTransactions_Run_Call {
	return &MockTransactions_Run_Call{Call: _e.mock.On("Run", context1, s, fn)}
}

func (_c *MockTransactions_Run_Call) Run(run func(context1 context.Context, s string, fn func(context.Context) error)) *MockTransactions_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(context.Context) error
		if args[2] != nil {
			arg2 = args[2].(func(context.Context) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactions_Run_Call) Return(err error) *MockTransactions_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactions_Run_Call) RunAndReturn(run func(context1 context.Context, s string, fn func(context.Context) error) error) *MockTransactions_Run_Call {
	_c.Call.Return(run)
	return _c
}
