// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/app/membership/model"
	model0 "github.com/chai-rs/handdraw-server/internal/workspace/model"
	"github.com/chai-rs/handdraw-server/pkg/cursor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockRepository
func (_mock *MockRepository) Accept(context1 context.Context, bytes []byte) (model.AccessResult, error) {
	ret := _mock.Called(context1, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 model.AccessResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (model.AccessResult, error)); ok {
		return returnFunc(context1, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) model.AccessResult); ok {
		r0 = returnFunc(context1, bytes)
	} else {
		r0 = ret.Get(0).(model.AccessResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(context1, bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockRepository_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - context1 context.Context
//   - bytes []byte
func (_e *MockRepository_Expecter) Accept(context1 any, bytes any) *MockRepository_Accept_Call {
	return &MockRepository_Accept_Call{Call: _e.mock.On("Accept", context1, bytes)}
}

func (_c *MockRepository_Accept_Call) Run(run func(context1 context.Context, bytes []byte)) *MockRepository_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Accept_Call) Return(accessResult model.AccessResult, err error) *MockRepository_Accept_Call {
	_c.Call.Return(accessResult, err)
	return _c
}

func (_c *MockRepository_Accept_Call) RunAndReturn(run func(context1 context.Context, bytes []byte) (model.AccessResult, error)) *MockRepository_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeMember provides a mock function for the type MockRepository
func (_mock *MockRepository) ChangeMember(context1 context.Context, roleChange model0.RoleChange) error {
	ret := _mock.Called(context1, roleChange)

	if len(ret) == 0 {
		panic("no return value specified for ChangeMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.RoleChange) error); ok {
		r0 = returnFunc(context1, roleChange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ChangeMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeMember'
type MockRepository_ChangeMember_Call struct {
	*mock.Call
}

// ChangeMember is a helper method to define mock.On call
//   - context1 context.Context
//   - roleChange model0.RoleChange
func (_e *MockRepository_Expecter) ChangeMember(context1 any, roleChange any) *MockRepository_ChangeMember_Call {
	return &MockRepository_ChangeMember_Call{Call: _e.mock.On("ChangeMember", context1, roleChange)}
}

func (_c *MockRepository_ChangeMember_Call) Run(run func(context1 context.Context, roleChange model0.RoleChange)) *MockRepository_ChangeMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model0.RoleChange
		if args[1] != nil {
			arg1 = args[1].(model0.RoleChange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ChangeMember_Call) Return(err error) *MockRepository_ChangeMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ChangeMember_Call) RunAndReturn(run func(context1 context.Context, roleChange model0.RoleChange) error) *MockRepository_ChangeMember_Call {
	_c.Call.Return(run)
	return _c
}

// Guests provides a mock function for the type MockRepository
func (_mock *MockRepository) Guests(context1 context.Context, s string) ([]model.Guest, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Guests")
	}

	var r0 []model.Guest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Guest, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Guest); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Guest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Guests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Guests'
type MockRepository_Guests_Call struct {
	*mock.Call
}

// Guests is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Guests(context1 any, s any) *MockRepository_Guests_Call {
	return &MockRepository_Guests_Call{Call: _e.mock.On("Guests", context1, s)}
}

func (_c *MockRepository_Guests_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Guests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Guests_Call) Return(guests []model.Guest, err error) *MockRepository_Guests_Call {
	_c.Call.Return(guests, err)
	return _c
}

func (_c *MockRepository_Guests_Call) RunAndReturn(run func(context1 context.Context, s string) ([]model.Guest, error)) *MockRepository_Guests_Call {
	_c.Call.Return(run)
	return _c
}

// Invitation provides a mock function for the type MockRepository
func (_mock *MockRepository) Invitation(context1 context.Context, s string) (model0.Invitation, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Invitation")
	}

	var r0 model0.Invitation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model0.Invitation, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model0.Invitation); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model0.Invitation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Invitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invitation'
type MockRepository_Invitation_Call struct {
	*mock.Call
}

// Invitation is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Invitation(context1 any, s any) *MockRepository_Invitation_Call {
	return &MockRepository_Invitation_Call{Call: _e.mock.On("Invitation", context1, s)}
}

func (_c *MockRepository_Invitation_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Invitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Invitation_Call) Return(invitation model0.Invitation, err error) *MockRepository_Invitation_Call {
	_c.Call.Return(invitation, err)
	return _c
}

func (_c *MockRepository_Invitation_Call) RunAndReturn(run func(context1 context.Context, s string) (model0.Invitation, error)) *MockRepository_Invitation_Call {
	_c.Call.Return(run)
	return _c
}

// Invitations provides a mock function for the type MockRepository
func (_mock *MockRepository) Invitations(context1 context.Context, s string, pageRequest model.PageRequest) ([]model0.Invitation, *cursor.Position, error) {
	ret := _mock.Called(context1, s, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Invitations")
	}

	var r0 []model0.Invitation
	var r1 *cursor.Position
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PageRequest) ([]model0.Invitation, *cursor.Position, error)); ok {
		return returnFunc(context1, s, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PageRequest) []model0.Invitation); ok {
		r0 = returnFunc(context1, s, pageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model0.Invitation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.PageRequest) *cursor.Position); ok {
		r1 = returnFunc(context1, s, pageRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cursor.Position)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, model.PageRequest) error); ok {
		r2 = returnFunc(context1, s, pageRequest)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_Invitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invitations'
type MockRepository_Invitations_Call struct {
	*mock.Call
}

// Invitations is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - pageRequest model.PageRequest
func (_e *MockRepository_Expecter) Invitations(context1 any, s any, pageRequest any) *MockRepository_Invitations_Call {
	return &MockRepository_Invitations_Call{Call: _e.mock.On("Invitations", context1, s, pageRequest)}
}

func (_c *MockRepository_Invitations_Call) Run(run func(context1 context.Context, s string, pageRequest model.PageRequest)) *MockRepository_Invitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.PageRequest
		if args[2] != nil {
			arg2 = args[2].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Invitations_Call) Return(invitations []model0.Invitation, position *cursor.Position, err error) *MockRepository_Invitations_Call {
	_c.Call.Return(invitations, position, err)
	return _c
}

func (_c *MockRepository_Invitations_Call) RunAndReturn(run func(context1 context.Context, s string, pageRequest model.PageRequest) ([]model0.Invitation, *cursor.Position, error)) *MockRepository_Invitations_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function for the type MockRepository
func (_mock *MockRepository) Invite(context1 context.Context, s string, s1 string, s2 *string, inviteParams model0.InviteParams, bytes []byte) (string, error) {
	ret := _mock.Called(context1, s, s1, s2, inviteParams, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, model0.InviteParams, []byte) (string, error)); ok {
		return returnFunc(context1, s, s1, s2, inviteParams, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string, model0.InviteParams, []byte) string); ok {
		r0 = returnFunc(context1, s, s1, s2, inviteParams, bytes)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string, model0.InviteParams, []byte) error); ok {
		r1 = returnFunc(context1, s, s1, s2, inviteParams, bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type MockRepository_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 *string
//   - inviteParams model0.InviteParams
//   - bytes []byte
func (_e *MockRepository_Expecter) Invite(context1 any, s any, s1 any, s2 any, inviteParams any, bytes any) *MockRepository_Invite_Call {
	return &MockRepository_Invite_Call{Call: _e.mock.On("Invite", context1, s, s1, s2, inviteParams, bytes)}
}

func (_c *MockRepository_Invite_Call) Run(run func(context1 context.Context, s string, s1 string, s2 *string, inviteParams model0.InviteParams, bytes []byte)) *MockRepository_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 model0.InviteParams
		if args[4] != nil {
			arg4 = args[4].(model0.InviteParams)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepository_Invite_Call) Return(s3 string, err error) *MockRepository_Invite_Call {
	_c.Call.Return(s3, err)
	return _c
}

func (_c *MockRepository_Invite_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 *string, inviteParams model0.InviteParams, bytes []byte) (string, error)) *MockRepository_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// Member provides a mock function for the type MockRepository
func (_mock *MockRepository) Member(context1 context.Context, s string, s1 string) (model.Member, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for Member")
	}

	var r0 model.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Member, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Member); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(model.Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Member_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Member'
type MockRepository_Member_Call struct {
	*mock.Call
}

// Member is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockRepository_Expecter) Member(context1 any, s any, s1 any) *MockRepository_Member_Call {
	return &MockRepository_Member_Call{Call: _e.mock.On("Member", context1, s, s1)}
}

func (_c *MockRepository_Member_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockRepository_Member_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Member_Call) Return(member model.Member, err error) *MockRepository_Member_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *MockRepository_Member_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (model.Member, error)) *MockRepository_Member_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type MockRepository
func (_mock *MockRepository) Members(context1 context.Context, s string, pageRequest model.PageRequest) ([]model.Member, *cursor.Position, error) {
	ret := _mock.Called(context1, s, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []model.Member
	var r1 *cursor.Position
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PageRequest) ([]model.Member, *cursor.Position, error)); ok {
		return returnFunc(context1, s, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PageRequest) []model.Member); ok {
		r0 = returnFunc(context1, s, pageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Member)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.PageRequest) *cursor.Position); ok {
		r1 = returnFunc(context1, s, pageRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cursor.Position)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, model.PageRequest) error); ok {
		r2 = returnFunc(context1, s, pageRequest)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type MockRepository_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - pageRequest model.PageRequest
func (_e *MockRepository_Expecter) Members(context1 any, s any, pageRequest any) *MockRepository_Members_Call {
	return &MockRepository_Members_Call{Call: _e.mock.On("Members", context1, s, pageRequest)}
}

func (_c *MockRepository_Members_Call) Run(run func(context1 context.Context, s string, pageRequest model.PageRequest)) *MockRepository_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.PageRequest
		if args[2] != nil {
			arg2 = args[2].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Members_Call) Return(members []model.Member, position *cursor.Position, err error) *MockRepository_Members_Call {
	_c.Call.Return(members, position, err)
	return _c
}

func (_c *MockRepository_Members_Call) RunAndReturn(run func(context1 context.Context, s string, pageRequest model.PageRequest) ([]model.Member, *cursor.Position, error)) *MockRepository_Members_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGuest provides a mock function for the type MockRepository
func (_mock *MockRepository) RemoveGuest(context1 context.Context, s string, s1 string) (model.Removal, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGuest")
	}

	var r0 model.Removal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.Removal, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.Removal); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(model.Removal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_RemoveGuest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGuest'
type MockRepository_RemoveGuest_Call struct {
	*mock.Call
}

// RemoveGuest is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockRepository_Expecter) RemoveGuest(context1 any, s any, s1 any) *MockRepository_RemoveGuest_Call {
	return &MockRepository_RemoveGuest_Call{Call: _e.mock.On("RemoveGuest", context1, s, s1)}
}

func (_c *MockRepository_RemoveGuest_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockRepository_RemoveGuest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_RemoveGuest_Call) Return(removal model.Removal, err error) *MockRepository_RemoveGuest_Call {
	_c.Call.Return(removal, err)
	return _c
}

func (_c *MockRepository_RemoveGuest_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (model.Removal, error)) *MockRepository_RemoveGuest_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockRepository
func (_mock *MockRepository) Revoke(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRepository_Expecter) Revoke(context1 any, s any) *MockRepository_Revoke_Call {
	return &MockRepository_Revoke_Call{Call: _e.mock.On("Revoke", context1, s)}
}

func (_c *MockRepository_Revoke_Call) Run(run func(context1 context.Context, s string)) *MockRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Revoke_Call) Return(err error) *MockRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Revoke_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// SharedBoardIDs provides a mock function for the type MockRepository
func (_mock *MockRepository) SharedBoardIDs(context1 context.Context, pageRequest model.PageRequest) ([]string, *cursor.Position, error) {
	ret := _mock.Called(context1, pageRequest)

	if len(ret) == 0 {
		panic("no return value specified for SharedBoardIDs")
	}

	var r0 []string
	var r1 *cursor.Position
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) ([]string, *cursor.Position, error)); ok {
		return returnFunc(context1, pageRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PageRequest) []string); ok {
		r0 = returnFunc(context1, pageRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PageRequest) *cursor.Position); ok {
		r1 = returnFunc(context1, pageRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*cursor.Position)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.PageRequest) error); ok {
		r2 = returnFunc(context1, pageRequest)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_SharedBoardIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharedBoardIDs'
type MockRepository_SharedBoardIDs_Call struct {
	*mock.Call
}

// SharedBoardIDs is a helper method to define mock.On call
//   - context1 context.Context
//   - pageRequest model.PageRequest
func (_e *MockRepository_Expecter) SharedBoardIDs(context1 any, pageRequest any) *MockRepository_SharedBoardIDs_Call {
	return &MockRepository_SharedBoardIDs_Call{Call: _e.mock.On("SharedBoardIDs", context1, pageRequest)}
}

func (_c *MockRepository_SharedBoardIDs_Call) Run(run func(context1 context.Context, pageRequest model.PageRequest)) *MockRepository_SharedBoardIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PageRequest
		if args[1] != nil {
			arg1 = args[1].(model.PageRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SharedBoardIDs_Call) Return(strings []string, position *cursor.Position, err error) *MockRepository_SharedBoardIDs_Call {
	_c.Call.Return(strings, position, err)
	return _c
}

func (_c *MockRepository_SharedBoardIDs_Call) RunAndReturn(run func(context1 context.Context, pageRequest model.PageRequest) ([]string, *cursor.Position, error)) *MockRepository_SharedBoardIDs_Call {
	_c.Call.Return(run)
	return _c
}
