// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/chai-rs/handdraw-server/internal/workspace/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokens creates a new instance of MockTokens. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokens(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokens {
	mock := &MockTokens{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokens is an autogenerated mock type for the Tokens type
type MockTokens struct {
	mock.Mock
}

type MockTokens_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokens) EXPECT() *MockTokens_Expecter {
	return &MockTokens_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockTokens
func (_mock *MockTokens) Issue(s string) (model.InvitationToken, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 model.InvitationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.InvitationToken, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.InvitationToken); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(model.InvitationToken)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokens_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokens_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - s string
func (_e *MockTokens_Expecter) Issue(s any) *MockTokens_Issue_Call {
	return &MockTokens_Issue_Call{Call: _e.mock.On("Issue", s)}
}

func (_c *MockTokens_Issue_Call) Run(run func(s string)) *MockTokens_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokens_Issue_Call) Return(invitationToken model.InvitationToken, err error) *MockTokens_Issue_Call {
	_c.Call.Return(invitationToken, err)
	return _c
}

func (_c *MockTokens_Issue_Call) RunAndReturn(run func(s string) (model.InvitationToken, error)) *MockTokens_Issue_Call {
	_c.Call.Return(run)
	return _c
}
