// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/idempotency/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockRepository
func (_mock *MockRepository) Begin(context1 context.Context, request model.Request) (model.Ticket, error) {
	ret := _mock.Called(context1, request)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 model.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Request) (model.Ticket, error)); ok {
		return returnFunc(context1, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Request) model.Ticket); ok {
		r0 = returnFunc(context1, request)
	} else {
		r0 = ret.Get(0).(model.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Request) error); ok {
		r1 = returnFunc(context1, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockRepository_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - context1 context.Context
//   - request model.Request
func (_e *MockRepository_Expecter) Begin(context1 any, request any) *MockRepository_Begin_Call {
	return &MockRepository_Begin_Call{Call: _e.mock.On("Begin", context1, request)}
}

func (_c *MockRepository_Begin_Call) Run(run func(context1 context.Context, request model.Request)) *MockRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Request
		if args[1] != nil {
			arg1 = args[1].(model.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Begin_Call) Return(ticket model.Ticket, err error) *MockRepository_Begin_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockRepository_Begin_Call) RunAndReturn(run func(context1 context.Context, request model.Request) (model.Ticket, error)) *MockRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type MockRepository
func (_mock *MockRepository) Complete(context1 context.Context, ticket model.Ticket, s string, n int) error {
	ret := _mock.Called(context1, ticket, s, n)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Ticket, string, int) error); ok {
		r0 = returnFunc(context1, ticket, s, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockRepository_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - context1 context.Context
//   - ticket model.Ticket
//   - s string
//   - n int
func (_e *MockRepository_Expecter) Complete(context1 any, ticket any, s any, n any) *MockRepository_Complete_Call {
	return &MockRepository_Complete_Call{Call: _e.mock.On("Complete", context1, ticket, s, n)}
}

func (_c *MockRepository_Complete_Call) Run(run func(context1 context.Context, ticket model.Ticket, s string, n int)) *MockRepository_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Ticket
		if args[1] != nil {
			arg1 = args[1].(model.Ticket)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Complete_Call) Return(err error) *MockRepository_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Complete_Call) RunAndReturn(run func(context1 context.Context, ticket model.Ticket, s string, n int) error) *MockRepository_Complete_Call {
	_c.Call.Return(run)
	return _c
}
