// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/collaboration/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockBackend
func (_mock *MockBackend) Apply(context1 context.Context, s string, s1 string, s2 string, n int64, bytes []byte) (model.Document, model.Access, error) {
	ret := _mock.Called(context1, s, s1, s2, n, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 model.Document
	var r1 model.Access
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, []byte) (model.Document, model.Access, error)); ok {
		return returnFunc(context1, s, s1, s2, n, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, []byte) model.Document); ok {
		r0 = returnFunc(context1, s, s1, s2, n, bytes)
	} else {
		r0 = ret.Get(0).(model.Document)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64, []byte) model.Access); ok {
		r1 = returnFunc(context1, s, s1, s2, n, bytes)
	} else {
		r1 = ret.Get(1).(model.Access)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, int64, []byte) error); ok {
		r2 = returnFunc(context1, s, s1, s2, n, bytes)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBackend_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockBackend_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - n int64
//   - bytes []byte
func (_e *MockBackend_Expecter) Apply(context1 any, s any, s1 any, s2 any, n any, bytes any) *MockBackend_Apply_Call {
	return &MockBackend_Apply_Call{Call: _e.mock.On("Apply", context1, s, s1, s2, n, bytes)}
}

func (_c *MockBackend_Apply_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, n int64, bytes []byte)) *MockBackend_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 []byte
		if args[5] != nil {
			arg5 = args[5].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockBackend_Apply_Call) Return(document model.Document, access model.Access, err error) *MockBackend_Apply_Call {
	_c.Call.Return(document, access, err)
	return _c
}

func (_c *MockBackend_Apply_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, n int64, bytes []byte) (model.Document, model.Access, error)) *MockBackend_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function for the type MockBackend
func (_mock *MockBackend) Check(context1 context.Context, s string, s1 string, s2 string) (model.Access, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 model.Access
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (model.Access, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) model.Access); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Get(0).(model.Access)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockBackend_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockBackend_Expecter) Check(context1 any, s any, s1 any, s2 any) *MockBackend_Check_Call {
	return &MockBackend_Check_Call{Call: _e.mock.On("Check", context1, s, s1, s2)}
}

func (_c *MockBackend_Check_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockBackend_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_Check_Call) Return(access model.Access, err error) *MockBackend_Check_Call {
	_c.Call.Return(access, err)
	return _c
}

func (_c *MockBackend_Check_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (model.Access, error)) *MockBackend_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockBackend
func (_mock *MockBackend) Load(context1 context.Context, s string, s1 string, s2 string) (model.Document, model.Access, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 model.Document
	var r1 model.Access
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (model.Document, model.Access, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) model.Document); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Get(0).(model.Document)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) model.Access); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		r1 = ret.Get(1).(model.Access)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(context1, s, s1, s2)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBackend_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockBackend_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockBackend_Expecter) Load(context1 any, s any, s1 any, s2 any) *MockBackend_Load_Call {
	return &MockBackend_Load_Call{Call: _e.mock.On("Load", context1, s, s1, s2)}
}

func (_c *MockBackend_Load_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockBackend_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_Load_Call) Return(document model.Document, access model.Access, err error) *MockBackend_Load_Call {
	_c.Call.Return(document, access, err)
	return _c
}

func (_c *MockBackend_Load_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (model.Document, model.Access, error)) *MockBackend_Load_Call {
	_c.Call.Return(run)
	return _c
}
