// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/chai-rs/handdraw-server/internal/collaboration/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockControls creates a new instance of MockControls. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControls(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControls {
	mock := &MockControls{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockControls is an autogenerated mock type for the Controls type
type MockControls struct {
	mock.Mock
}

type MockControls_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControls) EXPECT() *MockControls_Expecter {
	return &MockControls_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockControls
func (_mock *MockControls) Decode(s string, bytes []byte, b bool) (model.Control, error) {
	ret := _mock.Called(s, bytes, b)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 model.Control
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, bool) (model.Control, error)); ok {
		return returnFunc(s, bytes, b)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, bool) model.Control); ok {
		r0 = returnFunc(s, bytes, b)
	} else {
		r0 = ret.Get(0).(model.Control)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, bool) error); ok {
		r1 = returnFunc(s, bytes, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControls_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockControls_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - s string
//   - bytes []byte
//   - b bool
func (_e *MockControls_Expecter) Decode(s any, bytes any, b any) *MockControls_Decode_Call {
	return &MockControls_Decode_Call{Call: _e.mock.On("Decode", s, bytes, b)}
}

func (_c *MockControls_Decode_Call) Run(run func(s string, bytes []byte, b bool)) *MockControls_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControls_Decode_Call) Return(control model.Control, err error) *MockControls_Decode_Call {
	_c.Call.Return(control, err)
	return _c
}

func (_c *MockControls_Decode_Call) RunAndReturn(run func(s string, bytes []byte, b bool) (model.Control, error)) *MockControls_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type MockControls
func (_mock *MockControls) Encode(s string, control model.Control, b bool) ([]byte, error) {
	ret := _mock.Called(s, control, b)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, model.Control, bool) ([]byte, error)); ok {
		return returnFunc(s, control, b)
	}
	if returnFunc, ok := ret.Get(0).(func(string, model.Control, bool) []byte); ok {
		r0 = returnFunc(s, control, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, model.Control, bool) error); ok {
		r1 = returnFunc(s, control, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockControls_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockControls_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - s string
//   - control model.Control
//   - b bool
func (_e *MockControls_Expecter) Encode(s any, control any, b any) *MockControls_Encode_Call {
	return &MockControls_Encode_Call{Call: _e.mock.On("Encode", s, control, b)}
}

func (_c *MockControls_Encode_Call) Run(run func(s string, control model.Control, b bool)) *MockControls_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 model.Control
		if args[1] != nil {
			arg1 = args[1].(model.Control)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockControls_Encode_Call) Return(bytes []byte, err error) *MockControls_Encode_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockControls_Encode_Call) RunAndReturn(run func(s string, control model.Control, b bool) ([]byte, error)) *MockControls_Encode_Call {
	_c.Call.Return(run)
	return _c
}
