// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/identity/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileRepository creates a new instance of MockProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepository {
	mock := &MockProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileRepository is an autogenerated mock type for the ProfileRepository type
type MockProfileRepository struct {
	mock.Mock
}

type MockProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepository) EXPECT() *MockProfileRepository_Expecter {
	return &MockProfileRepository_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Resolve(context1 context.Context, profile model.Profile) (model.Profile, error) {
	ret := _mock.Called(context1, profile)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Profile) (model.Profile, error)); ok {
		return returnFunc(context1, profile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Profile) model.Profile); ok {
		r0 = returnFunc(context1, profile)
	} else {
		r0 = ret.Get(0).(model.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Profile) error); ok {
		r1 = returnFunc(context1, profile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockProfileRepository_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - context1 context.Context
//   - profile model.Profile
func (_e *MockProfileRepository_Expecter) Resolve(context1 any, profile any) *MockProfileRepository_Resolve_Call {
	return &MockProfileRepository_Resolve_Call{Call: _e.mock.On("Resolve", context1, profile)}
}

func (_c *MockProfileRepository_Resolve_Call) Run(run func(context1 context.Context, profile model.Profile)) *MockProfileRepository_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Profile
		if args[1] != nil {
			arg1 = args[1].(model.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Resolve_Call) Return(profile1 model.Profile, err error) *MockProfileRepository_Resolve_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *MockProfileRepository_Resolve_Call) RunAndReturn(run func(context1 context.Context, profile model.Profile) (model.Profile, error)) *MockProfileRepository_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
