// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chai-rs/handdraw-server/internal/identity/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Verify(context1 context.Context, accessToken model.AccessToken) (model.AuthIdentity, error) {
	ret := _mock.Called(context1, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 model.AuthIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AccessToken) (model.AuthIdentity, error)); ok {
		return returnFunc(context1, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.AccessToken) model.AuthIdentity); ok {
		r0 = returnFunc(context1, accessToken)
	} else {
		r0 = ret.Get(0).(model.AuthIdentity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.AccessToken) error); ok {
		r1 = returnFunc(context1, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - context1 context.Context
//   - accessToken model.AccessToken
func (_e *MockVerifier_Expecter) Verify(context1 any, accessToken any) *MockVerifier_Verify_Call {
	return &MockVerifier_Verify_Call{Call: _e.mock.On("Verify", context1, accessToken)}
}

func (_c *MockVerifier_Verify_Call) Run(run func(context1 context.Context, accessToken model.AccessToken)) *MockVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.AccessToken
		if args[1] != nil {
			arg1 = args[1].(model.AccessToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVerifier_Verify_Call) Return(authIdentity model.AuthIdentity, err error) *MockVerifier_Verify_Call {
	_c.Call.Return(authIdentity, err)
	return _c
}

func (_c *MockVerifier_Verify_Call) RunAndReturn(run func(context1 context.Context, accessToken model.AccessToken) (model.AuthIdentity, error)) *MockVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
